- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.3.0
  hooks:
  - id: check-added-large-files
  - id: debug-statements
- repo: git://github.com/pre-commit/mirrors-yapf
  sha: v0.22.0
  hooks:
  - id: yapf
